### ISSUE TITLE
Filters do not update automatically

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/ContentBlocker#94]
The customer (1716966) is using the content blocker with Yandex, he claims that the app does not update filters automatically despite it's set to do so.

![image](https://user-images.githubusercontent.com/15856304/34598292-80e06a96-f1f4-11e7-8018-7b06f1523389.png)

### Expected behavior

The content blocker updates filters automatically

### Actual behavior

The content blocker does not update filters, you can only do that manually

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| Adguard Content Blocker version:| 1.8.0
| Browser in use:| Yandex brouser build 0.526.
| Filters enabled in Adguard:| filtro inglese, filtro spyware, filtro widget social network, filtro annunci utili, filtro, annunci cellulari, filtro safari, filtro Easy list italy
| Device model:| Honor X6 
| Operating system and version:| Android 7
| Rooted or not? | No

**Comment by bugreport0** [comment]
Same issue here, Samsung Galaxy S8, Android 7.0, Samsung Browser 6.2.01.12, AdGuard 1.8

**Comment by ameshkov** [comment]
Cannot confirm it on Pixel + Oreo. I wonder what's wrong.

@bugreport0 how old could the filters become? AG prints when they were updated last time on the main screen.

**Comment by bugreport0** [comment]
Last time they were updated was on december 16. (Can't remember if i did that, or it was automatic), and i manually updated them yesterday.

**Comment by ameshkov** [comment]
Wow, that's a lot.

@nkartyshov any ideas?

**Comment by bugreport0** [comment]
When i set  Adguard to update only over wifi, automatic updates work as intended (at least in the last 2 days).

**Comment by bugreport0** [comment]
Any updates regarding this bug?

**Comment by ameshkov** [comment]
@bugreport0 we've tried reproducing (keeping eye on the update date) on a couple of devices -- no lock so far :(

**Comment by ameshkov** [comment]
What about you? Is it still happening?

**Comment by bugreport0** [comment]
Unfortunately, yes, even with the "update only via wifi" option enabled.

https://imgur.com/a/XvqPK
Took this screenshot few minutes ago.

**Comment by bugreport0** [comment]
Just checked on friends s8, and filters weren't updated since january 13th (the is the day I have installed adguard on his new phone).
So, it seems that filters stop auto updating when you don't open Adguard app for a few days, like it goes in some kind of sleep mode, but i have checked sleeping and battery saving aps in samsung device manager, and Adguard is not amoung them.

On both phones, filters did auto updates few minutes after opening app manualy, this is probably why you havent been able to reproduce bug.

**Comment by ameshkov** [comment]
> So, it seems that filters stop auto updating when you don't open Adguard app for a few days, like it goes in some kind of sleep mode

That might be the case indeed, thank you!

**Comment by bugreport0** [comment]
Today i have checked filters update status on colleagues Huawei p10 lite, with latest Samsung Internet Beta, and Adguard.

Same story, filters were from december.

**Comment by bugreport0** [comment]
When can we expect v2.0 release? :)

**Comment by ameshkov** [comment]
Rly-rly soon

**Comment by ameshkov** [comment]
@bugreport0 beta is available: https://play.google.com/store/apps/details?id=com.adguard.android.contentblocker

**Comment by bugreport0** [comment]
Switched to beta, we'll se se how automatic updates work, after few days...

Ps. Samsung Internet rating in Adguard is still 3.9, that info is not refreshed

**Comment by nkartyshov** [comment]
Fixed

**Comment by evgeniy-ADG** [comment]
Should it work in the 2.0.2 release? The user states it doesn't work.

**Comment by bugreport0** [comment]
Yes, problem is still here.
https://imgur.com/a/oOGU4

Took this screenshoot few minutes ago (february 12th, 23:05).

**Comment by nkartyshov** [comment]
@bugreport0 beta is available: https://play.google.com/store/apps/details?id=com.adguard.android.contentblocker

**Comment by ameshkov** [comment]
@bugreport0 did it help? It seems to work properly on our side.

**Comment by bugreport0** [comment]
https://imgur.com/a/pKu15

This is current status (took screenshot on feb 20. at 01:27)

This should be ok?

**Comment by ameshkov** [comment]
Yeah, seems so. Let's wait one more day to be 100% sure:)

**Comment by bugreport0** [comment]
Opening app do not trigger auto update anymore?

Everything looks fine today, i will report after few days of not opening app.

**Comment by bugreport0** [comment]
Few days after, everything still works fine.

Issue is fixed.
