### ISSUE TITLE
Update the information about browsers

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ContentBlocker#98]
Samsung and Yandex ratings have changed since the last time we checked it.

**Comment by duongvanbo789** [comment]
#98

**Comment by nkartyshov** [comment]
done

**Comment by bugreport0** [comment]
Samsung Internet rating  is not updated, still shows 3.9.

I'm on latest adguard beta.

**Comment by bugreport0** [comment]
It should be 4.4

**Comment by nkartyshov** [comment]
@bugreport0 Fixed, new  version: https://play.google.com/store/apps/details?id=com.adguard.android.contentblocker,
